### ISSUE TITLE
Rails 6 not adding pd , pd is identical to puts

### ISSUE THREAD

**Issue by jsonck** [AndyObtiva/puts_debuggerer#12] opened 2022-05-15 18:09 UTC
I added pd to my Rails 6 project but the output is identical to puts. Any ideas?

>> Rails.version
=> "6.1.4.1"
>> pd 'test'
=> "test"

**Comment by AndyObtiva** [comment] 2022-05-15 18:24
Please provide this info:
- Ruby version
- Operating system
- CPU Architecture (x86_64/x64 or ARM64?)
- puts_debuggerer gem version
- What Bundler group did you configure puts_debuggerer in (all, development, or test)?
- Where (what file) is the `pd` method getting called from (model, controller, configuration, etc...)?

I just tried `pd` in a scaffolded controller inside a Rails 6.1.4.1 created app in a x86_64 Mac, and it worked:
```
[PD] /Users/andymaleh/code/rails-jruby-app-6-1-4-1/app/controllers/blog_posts_controller.rb:6
   > pd @blog_posts = BlogPost.all
  => [
    [0] #<BlogPost:0x00007fb02706e558> {
                :id => 1,
             :title => "Hello, World!",
              :body => "Hello there everybody!",
        :created_at => Sun, 15 May 2022 18:21:03.723217000 UTC +00:00,
        :updated_at => Sun, 15 May 2022 18:21:03.723217000 UTC +00:00
    }
]
```

**Comment by AndyObtiva** [comment] 2022-05-15 18:26
By the way, one thing to note is that the return value of `pd` is always the object passed to it as an argument, minus options (meaning it acts as if you did not call `pd` at all to avoid interfering with the logic where it is invoked from)

**Comment by AndyObtiva** [comment] 2022-05-18 20:16
I am closing this issue as an "Unable to reproduce" issue. You are welcome to respond if you really have the issue and can supply the troubleshooting info to help fix it.

**Closed by AndyObtiva** 2022-05-18 20:16 UTC
